llm:
  embeddingModel: "text-embedding-ada-002"
  openai:
    key: "your-openai-key"

vector:
  scoreThreshold: 0.8
  weaviate:
    host: "localhost:8080"
    scheme: "http"

document:
  localDir:
    directory: sop

prometheus:
  address: "http://localhost:9090"
